### ISSUE TITLE
Add "Comparison with Node.js" chapter

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#13]
Ref https://github.com/denoland/deno/issues/6844

- [ ] Make a separate chapter about differences between Deno and Node
- [ ] Compare most common Node APIs with Deno equivalents
- [ ] Write about popular Node packages that are built into `deno_std`

**Comment by kitsonk** [comment]
Isn't this already addressed by: https://deno.land/manual@v1.12.1/npm_nodejs. Anything missing should just be added to this.  I don't think it is "beneficial" to just have a chapter dedicated to how Node.js is different than Deno.

**Comment by bartlomieju** [comment]
Yep, that makes sense, I must have missed that new chapter.

**Comment by kitsonk** [comment]
@bartlomieju you reviewed it and I addressed several of your comments: https://github.com/denoland/deno/pull/11419 🤣
