### ISSUE TITLE
Add FS / HTTP streaming examples

### ISSUE THREAD

**Issue by lucacasonato** [denoland/manual#133]
Some questions come up on the community Discord on a regular basis, that we should probably add examples for in the manual:

- How do I stream a response from `fetch` to a file on disk?
- How do I stream a file on disk to a response for `Deno.serveHttp`?
- How do I upload stream a file to a web service via fetch?

**Comment by bartlomieju** [comment]
> I'd like to argue that the [File Server example](https://deno.land/manual@v1.15.3/examples/file_server#file-server) should be rewritten to explain how to build a file server from scatch, introducing people to the idea of file streaming. Right now, the example only tells people that they can use an off-the-shelf solution from the std. I don't find the example in its current state to be particularly useful at learning Deno.
> 
> What do you think?

That sounds good! PRs are welcome

**Comment by tommy-josepovic** [comment]
Great! I'll give it a try! 😄
