### ISSUE TITLE
Update "Embedding Deno" chapter

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#15]
"Embedding Deno" chapter is very lax, it should be updated to mention `deno_core` and `deno_runtime` crates.

Would be great to link to some existing projects that use those crates, eg.
https://github.com/lucacasonato/wgpu_cts_runner

**Comment by bartlomieju** [comment]
Link to examples available in `deno_core`:
https://github.com/denoland/deno/tree/main/core/examples

**Comment by kt3k** [comment]
Maybe we should link to your blog post? https://deno.com/blog/roll-your-own-javascript-runtime

**Comment by NinekoTheCat** [comment]
will work on it
