### ISSUE TITLE
Update "Tools" chapter

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#17]
The "Tools" section is quite outdated and missing a lot of crucial info, examples:

- "Formatter" doesn't mention all supported languages
- "REPL" doesn't mention TS support, and static imports declaration (https://deno.com/blog/v1.12#repl-gets-support-for-typescript-and-more-improvements)
- "Linter" doesn't link to https://lint.deno.land with description for each rule

**Comment by jaydenseric** [comment]
Also, the formatter docs (and `deno fmt --help`) don't explain or show an example for linting particular directories, or particular file types. Are globs supported? What kinds of globs?
