### ISSUE TITLE
Update "Read-eval-print-loop" section with information about Node compatbility

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#194]
REPL supports running in compatibility mode (`deno repl --compat --unstable`), but there
are currently no information about it on the page: https://deno.land/manual@v1.17.1/tools/repl

We should add following info:
- that `--compat` is supported
- that `require` and Node resolution is available
- that built-in Node.js modules are already loaded: https://github.com/denoland/deno/pull/13127

**Comment by lino-levan** [comment]
The `--compat` flag has been dropped from Deno. This issue should probably be closed.
