### ISSUE TITLE
TypeScript: How to setup external module type definition like @types

### ISSUE THREAD

**Issue by ryota-murakami** [denoland/manual#20]
In the [following section](https://deno.land/manual@v1.12.1/typescript/types#providing-types-when-importing) in the TypeScript guide explaining how to apply `d.ts` file that's you have already.

But person who are familiar Node.js's npm package like me, execute command like `npm install -D @types/react` and then get type definition file from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).  

As a one of React/Node.js developer, current manual seems like unclear to get type definition file of external modules.  

I think it's better if the manual is covering that concern clearly.  

Thank you. 🤗

**Comment by kitsonk** [comment]
There is [this section](https://deno.land/manual@v1.12.1/npm_nodejs/cdns#deno-quotfriendlyquot-cdns) which talks about CDNs that can provide types automatically.

A more clear [FAQ](https://deno.land/manual@v1.12.1/typescript/faqs) though could provide both pieces of information at the same time, noting that most code target for Deno is either written in TypeScript or automatically provides its types, so the type acquisition is really the concern when trying to leverage code written for Node.js or on npm.

**Comment by ryota-murakami** [comment]
@kitsonk I understood it very well.
Thank you very much for your excellent answer. 😄

**Comment by ryota-murakami** [comment]
@kitsonk This issue have been solved but still opening.  
Is there any relation to following Discord server announcement?

> PSA
>
> We want to drastically improve Deno's documentation (https://deno.land/manual) in the near future.
>
> I've opened several issues with stuff that IMO feels like it needs updating: https://github.com/denoland/manual/issues
>
> However I am biased in this regard as I work on Deno daily, so what needs improvement in my opinion might be drastically 
different than what community feels is lacking in the documentation. 
>
> So hereby I'm encouraing you to open issues in that repo with subjects that you found yourself lost when trying to learn about them.

**Comment by kitsonk** [comment]
The issue is tagged as `help wanted` to indicate that the community could contribute to making the documentation more clear by adding to the TypeScript FAQ section.

**Comment by ryota-murakami** [comment]
@kitsonk Got it, thanks!
