### ISSUE TITLE
Docs: doc.deno.land link in "First steps" page is broken

### ISSUE THREAD

**Issue by martixy** [denoland/manual#209]
The link to the deno docs on the ["First steps"](https://deno.land/manual@v1.5.1/getting_started/first_steps) page is broken.

It leads to this URL: https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts

![Deno broken link](https://user-images.githubusercontent.com/8262590/150235142-2b8ca6d0-3ad4-4ed9-8134-bd8686427ded.png)

**Comment by kitsonk** [comment]
You are using a very outdated version of the manual (v1.5.1 to be specific).  The current (and recent) versions of the manual are working as expected.

Was there a link somewhere that led you to the very outdated version of the manual?

**Comment by martixy** [comment]
How odd. I have no idea how I have landed on such an outdated version. But I must have followed a link there. I set up deno yesterday, but didn't get around to tinker with it. And now I don't remember how I got to the docs.

I suppose there's not much to do here unless I remember how I arrived at the outdated docs.
