### ISSUE TITLE
typescript/migration page on v1.18.0 not found

### ISSUE THREAD

**Issue by jlecordier** [denoland/manual#214]
When navigating to <https://deno.land/manual@v1.18.0/typescript/migration>, a 404 is displayed. The file at <https://deno.land/x/manual@v1.18.0/typescript/migration.md> is not found.

When clicking on the "Edit on GitHub" button, we are redirected to <https://github.com/denoland/manual/blob/v1.18.0/typescript/migration.md>, where a content does exist.

**Comment by kitsonk** [comment]
It only seems to be an issue with v1.18.0 of the manual, several before it and v1.18.1 and main after it are both ok.

**Comment by kt3k** [comment]
Closing as the issue doesn't seem persisting in recent versions:
- https://deno.land/manual@v1.27.0/typescript/migration
- https://deno.land/manual@v1.26.0/typescript/migration
