### ISSUE TITLE
Schematic diagram in contributing/architecture is broken.

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/manual#235]
Hi. I found that schematic diagram image in [contributing/architecure section](https://deno.land/manual@v1.19.1/contributing/architecture#schematic-diagram) is broken.

I found [the original image](
https://github.com/denoland/deno/blob/f96aaa802b245c8b3aeb5d57b031f8a55bb07de2/website/images/schematic_v0.2.png) (I think this image was missing when migrating to https://github.com/denoland/dotland) but I think this image is a pretty old one and I wanna know there can be any update in this diagram.
If there isn't, please upload this image on dotland or manual. thanks :)

**Comment by xgqfrms** [comment]
# docs bug

> deno architecture diagram

https://deno.land/manual/contributing/architecture

https://github.com/denoland/manual/blob/v1.21.1/contributing/architecture.md
