### ISSUE TITLE
502 Bad Gateway (Deployment Failed)

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/manual#268]
The manual is not reachable. It looks like the deployment failed.
![image](https://user-images.githubusercontent.com/12952387/160606802-968d0912-5778-4c4f-9bae-38a5b2e1a7ce.png)
Is anyone aware of this already?

**Comment by lucacasonato** [comment]
That is available for me. What region are you in?

**Comment by KnorpelSenf** [comment]
I'm currently located in Trondheim, Norway.

**Comment by lucacasonato** [comment]
Is it fixed now?

**Comment by KnorpelSenf** [comment]
Yes! Thanks!
