### ISSUE TITLE
Make more examples platform agnostic

### ISSUE THREAD

**Issue by dsherret** [denoland/manual#27]
The following parts of the manual aren't as good as they could be for users more familiar with Windows:

1. https://deno.land/manual@v1.12.2/getting_started/first_steps#reading-a-file - Uses `/etc/passwd`
2. https://deno.land/manual@v1.12.2/getting_started/first_steps#tcp-server - Uses netcat. In other parts of the manual it at least mentions this is Linux/MacOS only (ex. https://deno.land/manual@v1.12.2/examples/tcp_echo)
3. https://deno.land/manual@v1.12.2/getting_started/command_line_interface#script-source - Uses `cat`, which is not available on the command line in windows and code does not work in powershell. Maybe this one is not a big deal to change.
4. https://deno.land/manual@v1.12.2/getting_started/permissions#permissions-allow-list - Talks about the `/usr` and `/etc` directory. Tries to access `/etc/passwd`

https://discord.com/channels/684898665143206084/684898665151594506/870313956982554645

**Comment by nhrones** [comment]
Manual 7.9 TCP echo server.  The example uses netcat to test/run example.

**Comment by nhrones** [comment]
I could find no other areas of the manual that would not work for a Windows user. Many areas toward the end of the manual have explicit instructions for usage on Windows.  Thanks again.

**Comment by nhrones** [comment]
@dsherret  Window work around.
For Windows users, in place of netcap,
enable optional Windows feature 'telnet
in vscode, open second terminal and enter>  telnet 127.0.0.1 8080
then type some text
characters will be echoed one at a time.
