### ISSUE TITLE
Add instruction for running dev server locally

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#3]

**Comment by WingZer0123** [comment]
@bartlomieju 

This project seemed like a good place to start for me to get to know how to use the tool better. A simple 8080 port server example can be made with a simple text serving example for the requests coming in using the imported serve module from `https://deno.land/std@0.161.0/http/server.ts`. Is that what you had in mind?

**Comment by WingZer0123** [comment]
@kt3k This was my mistake and I read that incorrectly and probably should have asked first. How is this typically run via a specific http-server deno module?

**Comment by kt3k** [comment]
This manual is part of `dotland` project. https://github.com/denoland/dotland

I documented how to start it in #424

**Comment by WingZer0123** [comment]
So this would be in the main README and not in an example?
