### ISSUE TITLE
Typecheck examples in the manual

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#31]
With https://github.com/denoland/deno/pull/11421 landed, we can now use `canary` channel to type check examples in the manual.

Since manual uses `$STD_VERSION` tags, we'll need to add an import map file, that will map to latest version of standard library.

This functionality should be added as part of CI script.

CC @caspervonb

**Comment by caspervonb** [comment]
>  that will map to latest version of standard library.

Probably want to point this directly to GitHub so that it refers to "canary" std?
