### ISSUE TITLE
Dead link to deno.land/tools

### ISSUE THREAD

**Issue by aslilac** [denoland/manual#331]
https://deno.land/manual
https://github.com/denoland/manual/blob/v1.22.2/introduction.md

Probably worth searching for other broken links to the same page as well

**Comment by GJZwiers** [comment]
Seems like a bug with how https://deno.land/manual handles `./` in the Markdown links. They are working normally when navigating to https://deno.land/manual/introduction though.

**Comment by rbarbazz** [comment]
It seems this is caused by https://github.com/denoland/dotland/issues/2164.

**Comment by GJZwiers** [comment]
This was fixed in https://github.com/denoland/dotland/pull/2177.

**Comment by aslilac** [comment]
I think you're right. :)
