### ISSUE TITLE
Typechecking not enabled by default is not clearly indicated in the docs

### ISSUE THREAD

**Issue by CavalcanteLucas** [denoland/manual#348]
I'm new here, and I spent quite some time to figure out that typechecking is not enabled by default since version `1.23`.

Please check out this discussion for what I think might be a common question for begginers:
https://stackoverflow.com/questions/72812645/how-to-activate-typescript-verification-of-types/72812958?noredirect=1#comment128609270_72812958

I couldn't easily find about the use of `--check` flag on the documentation.
So I started to spend a lot of time on how to create a `tsconfig.json`, then I started to wonder about errors in the linter VSCode is using, and sundelly hours have passed.

Thus I believe maybe that should be an important thing to stress for new learners..

**Comment by bartlomieju** [comment]
Thanks, it seems docs got out of date on this topic. I'll make sure to update them next week.

**Comment by CavalcanteLucas** [comment]
Glad to be useful! Please let me know if I can contribute further anyhow.

**Comment by bartlomieju** [comment]
@CavalcanteLucas if you want to contribute, it'd be great if these two sections from the blog posts could be incorporated into the manual:
- https://deno.com/blog/v1.22#default-type-checking-behavior-has-been-updated
- https://deno.com/blog/v1.23#no-type-checking-by-default

**Comment by CavalcanteLucas** [comment]
Of course, I'd be glad to do it!
Please allow me to read those posts carefully though.

**Comment by CavalcanteLucas** [comment]
Question:

Has the impact of the [environment variable](https://deno.land/manual/getting_started/setup_your_environment#environment-variables) `DENO_FUTURE_CHECK` been changed?

**Comment by jsejcksn** [comment]
> Question:
> 
> Has the impact of the [environment variable](https://deno.land/manual/getting_started/setup_your_environment#environment-variables) `DENO_FUTURE_CHECK` been changed because of these updates?

@CavalcanteLucas It no longer has an effect on `deno run` now that type-checking is disabled without the `--check` argument.

**Comment by CavalcanteLucas** [comment]
I believe I should close this Issue, as PR#357 has been merged.
