### ISSUE TITLE
Auto format PR's changes

### ISSUE THREAD

**Issue by kt3k** [denoland/manual#371]
We should create github action workflow which automatically formats the files in PR's branch and push it to that branch if there's any unformatted files

**Comment by bartlomieju** [comment]
When we set up this repo @lucacasonato and I tried to add auto-format but there was a GH Actions limitation that didn't allow to push to contributors branch. I'm not sure if that's still the case

**Comment by ayame113** [comment]
If there is a limit on push from GitHub Actions, how about using [reviewdog](https://github.com/reviewdog/reviewdog) to suggest a format change?

For example, https://github.com/ayame113/js-playground/pull/4#discussion_r932054275 and https://github.com/ayame113/js-playground/blob/5be8bfc0fba70c849cbfcacaf2c97764d76d15c0/.github/workflows/suggest_change.yml

![image](https://user-images.githubusercontent.com/40050810/181485676-a51f1963-7093-4c60-8470-ec7542b93951.png)

**Comment by kt3k** [comment]
> If there is a limit on push from GitHub Actions, how about using [reviewdog](https://github.com/reviewdog/reviewdog) to suggest a format change?

Sounds like a good workaround to me
