### ISSUE TITLE
Add section on connecting to databases/datastores

### ISSUE THREAD

**Issue by kitsonk** [denoland/manual#383]
The top most searched for terms in the manual are all related to connecting to databases/datastores and we really lack this type of coverage in the manual.  We should have a section dedicated this and ensure we provide details on use cases for the following:

- Indicate that `localStorage` exists by default in Deno
- Cover off these searched for persistence layers (in descending order of popularity over the last 30 days)
  - supabase
  - postgres
  - sqlite
  - mongo
  - mysql
  - firebase

**Comment by erfanium** [comment]
Deno team doesn't have a clear solution for drivers. we have some native drivers created by denodrivers team which they are not good for now. on the other side, The Deno team wants official node drivers to be worked on Deno (ref: https://github.com/denoland/deno/issues/12577).

I think we should make a decision here. made good Deno native drivers from zero **OR** use node drivers

**Comment by rahulvarshney** [comment]
A real simple "Hello World" example for Supabase would be nice, showing how to get a single value from supabase and how to print that value to index.tsx
