### ISSUE TITLE
Add npm support to Node compat chapter

### ISSUE THREAD

**Issue by GJZwiers** [denoland/manual#388]
The new npm URLs can be documented somewhere in the `Interoperating with Node and NPM` chapter.

**Comment by jsejcksn** [comment]
Ref: https://github.com/denoland/deno/pull/15678

It looks like this section needs to be refactored now.

**Comment by kitsonk** [comment]
The manual is going through an extensive rewrite at the moment and this is on the todo list.

Closing, knowing it is being tracked specifically under the rewrite work holistically.
