### ISSUE TITLE
Use asdf as the recommended installer?

### ISSUE THREAD

**Issue by eric-burel** [denoland/manual#393]
I've recently started to use [asdf](https://asdf-vm.com/) and I think it's a very interesting way to install packages:

- not restricted to JS ecosystem, contrary to Node.js NVM and Volta, Python pyvenv and so on
- same commands on all systems
- can handle versioning per project elegantly, with tracking for the whole team

The Deno plugin lives there: https://github.com/asdf-community/asdf-deno

Install looks like this:
```sh
asdf plugin-add deno https://github.com/asdf-community/asdf-deno.git
asdf install deno latest
asdf global deno latest
# asdf local deno latest # if you want to specify a specific version per project
```

Btw, the "edit" button on in the manual web page lead to a branch specific version on GitHub that is not really editable (https://github.com/denoland/manual/blob/v1.25.0/getting_started/installation.md, edit button says "you must be on a branch to edit"), which prevented me from opening a PR directly, I don't know if this process could be improved?

**Comment by jsejcksn** [comment]
@eric-burel I thought I remembered it being listed in the [installation](https://deno.land/#installation) section of the homepage (but maybe I'm misremembering that). It's still in the [readme](https://github.com/denoland/deno_install/tree/281488a512315e31b57984d41b67decb11864816#install-and-manage-multiple-versions) for the `deno_install` repo, which is linked from that section in the home page. Is that what you meant?

**Comment by eric-burel** [comment]
You seem to have 3 pages that are not completely consistent:
- https://deno.land/manual@v1.25.2/getting_started/installation: from the getting started page, lists the "scripts" approaches + OS specific approaches but not asdf.
- https://deno.land/#installation: the website page, lists the "scripts" approaches
- https://github.com/denoland/deno_install/tree/281488a512315e31b57984d41b67decb11864816#install-and-manage-multiple-versions: the deno_install Readme, lists all

I propose to always have:
1) the asdf approach as the recommended cross-platform multi-versions approach, especially if user intend to have multiple deno projects + may also want to adopt asdf for their node projects
2) the script approaches that are turnkey
3) a list of other various package managers that can install Deno

**Comment by jsejcksn** [comment]
> 1. the asdf approach as the recommended cross-platform multi-versions approach

@eric-burel I love using `asdf`, but it's [not cross-platform](https://github.com/asdf-vm/asdf/issues/450#issuecomment-1159851199). It only supports unix-like operating systems, and native usage on Windows is definitely a large target for Deno.

**Comment by eric-burel** [comment]
Ah didn't know that limitation indeed. So at least it would be worth making the documentation consistent, and perhaps recommend Asdf only for unix systems + Windows for WSL for users that intend to manage multiple versions of Deno (agency, freelancers etc.). It's still a relatively good solution if it supports most system apart native Windows, for which you have other solutions.
