### ISSUE TITLE
Tutorial Broken or just me?

### ISSUE THREAD

**Issue by GrosSacASac** [denoland/manual#41]
https://www.reddit.com/r/Deno/comments/p0q9sk/tutorial_broken_or_just_me/

**Comment by satyarohith** [comment]
I tested the example on Windows, and it's working as expected. However, we can improve the example's output to be Windows compatible, and we've https://github.com/denoland/manual/issues/27 for that.

I'm closing this issue, considering the issue as user-specific. I'm following up with the user on Reddit.
