### ISSUE TITLE
Code coverage documentation need further explanation

### ISSUE THREAD

**Issue by cknight** [denoland/manual#42]
Code coverage help is as follows:
```
--coverage=<coverage>          
            UNSTABLE: Collect coverage profile data
```
No explanation is given on the parameter value (e.g. `<coverage>`), nor is this explained in the manual https://deno.land/manual@v1.7.4/testing#test-coverage.

It's not clear at all what value should be given.

**Comment by bartlomieju** [comment]
This is actually explained quite well in latest version: https://deno.land/manual@v1.13.0/testing/coverage

**Comment by cknight** [comment]
Thanks @bartlomieju , two additional thoughts here:
1. My link above was the top hit on google to mention code coverage, which now that I look at it more closely is clearly out of date. I wonder if there are ways to avoid google returning out of date manual links?
2. The latest manual page does indeed explain this well, but the CLI help does not (and still lists this as UNSTABLE which I don't believe it is?).  A proposal:
```
--coverage=<coverage_dir>
      Collect coverage profile data into <coverage_dir>
```

**Comment by bartlomieju** [comment]
> Thanks @bartlomieju , two additional thoughts here:
> 
> 1. My link above was the top hit on google to mention code coverage, which now that I look at it more closely is clearly out of date. I wonder if there are ways to avoid google returning out of date manual links?

I'm not sure about that, @lucacasonato thoughts?

> 2. The latest manual page does indeed explain this well, but the CLI help does not (and still lists this as UNSTABLE which I don't believe it is?).  A proposal:
> 
> ```
> --coverage=<coverage_dir>
>       Collect coverage profile data into <coverage_dir>
> ```

This looks better, could you upstream that in `deno` repo?
