### ISSUE TITLE
CSS & deploy server 

### ISSUE THREAD

**Issue by loglost** [denoland/manual#433]
Hello, Nice to meet you.
I'm a beginner among beginners just starting to learn development.

I was very excited when I heard the benefits of Dino.
But when I set up even one css, I was very confused. No, rather, I've been looking for twind and looking for a way all week, but the explanation below wasn't enough for me.

https://deno.land/manual@v1.26.0/jsx_dom/twind

Q1.
twind was totally different from css and very complicated. The explanation in the link below was insufficient information for me to be beyond the sea.
Is there an easy way to use css?

Q2.
The description was to connect the server using supabase. After much trouble, I managed to automatically deploy it, but the database could not be connected. I'm a beginner, so I'll work harder to find out how to do this, but I hope there's an easy guide.

Another question is that it seems to be talking about the server for automatic distribution that you use while paying a monthly fee of $10, but it seems that Data Ebisu is not included. Are the small amounts listed below $10/month an additional charge for each time the suggested capacity is exceeded?

**Comment by kt3k** [comment]
Check out #help channel of our discord server https://discord.gg/deno . Here is the place for discussing the improvement/fix of our manual, and not for general questions in development.

(For css question, aleph provides a way to simply write css. See https://alephjs.org/docs/basic-concepts/css-support
