### ISSUE TITLE
Support for type-checking npm packages not yet documented

### ISSUE THREAD

**Issue by GJZwiers** [denoland/manual#434]
The new chapter on using npm in Deno says that 'type checking is not yet supported' but this is possible as of v1.27.0: https://deno.com/blog/v1.27#improvements-to-npm-compatibility

https://github.com/denoland/manual/blob/0396df756d4e7a43b0d97e243f9f8b073721726b/node/npm_specifiers.md?plain=1#L50

**Comment by dsherret** [comment]
This has been updated.
