### ISSUE TITLE
Missing cache_api.md file 

### ISSUE THREAD

**Issue by geetsww** [denoland/manual#436]
Hello, 

I just found that this link is broken: https://deno.land/manual@v1.28.0/runtime/cache_api

And it seems like there isn't a `runtime/cache_api.md` file in this repo.

**Comment by GJZwiers** [comment]
Also https://deno.land/manual@v1.28.0/runtime/navigator_api doesn't exist

**Comment by Mongkol67** [comment]
> Hello,
> 
> I just found that this link is broken: https://deno.land/manual@v1.28.0/runtime/cache_api
> 
> And it seems like there isn't a `runtime/cache_api.md` file in this repo.
