### ISSUE TITLE
Add info about using DOM in Deno

### ISSUE THREAD

**Issue by bartlomieju** [denoland/manual#45]
https://github.com/denoland/deno/issues/6794#issuecomment-885593699

**Comment by kitsonk** [comment]
Yeah, and I said I would take a first draft of it, but that slipped down my list as well.  Will try to do so soon.

**Comment by bartlomieju** [comment]
> Yeah, and I said I would take a first draft of it, but that slipped down my list as well. Will try to do so soon.

Thanks!

**Comment by jsejcksn** [comment]
Hi @kitsonk: I'm checking back in on this. Bartek said back in July that everyone following the closed tracking issue could expect some guidance on this in manual "soon", and I'm wondering if you can provide an updated estimation at this point. Thanks!

**Comment by kitsonk** [comment]
I am finally starting work on this... Hopefully will have something in a couple days.

**Comment by jespertheend** [comment]
If anyone runs across this, this worked for me:
```js
// jsdomtest.js

import {JSDOM} from "https://cdn.esm.sh/jsdom";

const dom = new JSDOM();
const el = dom.window.document.createElement("div");
console.log(el);
```

Then run with
```
deno run --unstable --no-check jsdomtest.js
```
which logs
```
HTMLDivElement {}
```

**Comment by VTCAKAVSMoACE** [comment]
How did you get this to work? JSDOM checks vm.isContext, which is marked as not implemented. @jespertheend

**Comment by jespertheend** [comment]
I'm currently importing from `https://esm.sh/jsdom@19.0.0?no-check&pin=v64` with Deno `1.24.1`.
I wouldn't be surprised if upgrading either jsdom, esm.sh or deno breaks this setup.

**Comment by VTCAKAVSMoACE** [comment]
That did it! Though, I would really like to use the new version if possible. A note on the manual page would be good in the meantime while I think of how to insert that vm shim that jsdom provides.
