### ISSUE TITLE
Atom editor deprecation

### ISSUE THREAD

**Issue by GJZwiers** [denoland/manual#456]
On December 15 [Atom will be sunset](https://github.blog/2022-06-08-sunsetting-atom/). It says 'Atom package management will stop working', so it's possible https://atom.io/packages/atom-ide-deno will no longer work from that date. Maybe the [paragraph on Atom support in Deno](https://github.com/denoland/manual/blob/main/getting_started/setup_your_environment.md#atom) should be removed.

**Comment by ayame113** [comment]
For reference, GitHub just stopped developing Atom Editor, but the community continues to develop it.
https://pulsar-edit.dev/about.html#the-team
The atom-ide-ui extension should still work within those editors.

That said, it should be fine to remove the Atom Editor section from the manual. Once the community version of Atom is stable enough, we can re-add the manual entries.

**Comment by GJZwiers** [comment]
If the package stays usable there is no real need to remove the info, maybe just rename Atom to Pulsar?

**Comment by ayame113** [comment]
> If the package stays usable there is no real need to remove the info, maybe just rename Atom to Pulsar?

It would be nice to fix the link as well.

- https://atom.io/packages/atom-ide-deno -> https://web.pulsar-edit.dev/packages/atom-ide-deno
- https://atom.io/packages/atom-ide-base -> https://web.pulsar-edit.dev/packages/atom-ide-base
