### ISSUE TITLE
Code and text are out of sync for "Putting it all together in an HTTP server" example

### ISSUE THREAD

**Issue by danvk** [denoland/manual#464]
See https://deno.land/manual@v1.28.2/getting_started/first_steps#putting-it-all-together-in-an-http-server and https://github.com/denoland/manual/blob/7ecb7fde3a161932f5b088758674cb2f5932f492/getting_started/first_steps.md?plain=1#L141

It looks like the code and the text got out of sync here:

- The example code introduces a `port` variable that isn't used.
- The text says that the code "Import[s] a third party module, `url_join`" but the code does not do this.
- "In the handler function, use `url_join` to join together a complex Github url" -- the example code does not do this.
- "Write the response body to a local file." -- the example code does not do this.
- "Note that you need to give both network and write permissions." -- for the code as written, you do not need to give it write permissions.
- The `console.log` in the code seems superfluous. When I run the code, I see "Listening on http://localhost:8000" printed twice, so I think the `serve` call must do this on its own.

Finally, small nit: it's GitHub (capital "H"), not Github.

**Comment by E-Randz** [comment]
Hey there,

It appears that part of this has already been addressed in that v1.30.0 no longer referrences `url_join`. The following issues still apply though:

- The example code introduces a port variable that isn't used.
- "Write the response body to a local file." -- the example code does not do this.
- "Note that you need to give both network and write permissions." -- for the code as written, you do not need to give it write permissions.
- The console.log in the code seems superfluous. When I run the code, I see "Listening on http://localhost:8000/" printed twice, so I think the serve call must do this on its own.
- Finally, small nit: it's GitHub (capital "H"), not Github.

I'm happy to take this on and will open a PR shortly.

**Comment by E-Randz** [comment]
Hi @kt3k, would it be possible to add me as a contributor to this repo so I can push my branch and open a PR for this? 🙏

**Comment by kt3k** [comment]
Please fork this repository by clicking the right top 'fork' button and create a PR from your fork

**Comment by kt3k** [comment]
fixed by #544
