### ISSUE TITLE
Warning 'port' is declared but its value is never

### ISSUE THREAD

**Issue by silvioprog** [denoland/manual#478]
This warning is raised from the example `http_server.ts` at [`Putting it all together in an HTTP server`](https://deno.land/manual@v1.28.3/getting_started/first_steps#putting-it-all-together-in-an-http-server).

**Comment by silvioprog** [comment]
Also:

```
'request' is declared but its value is never
```

**Comment by bartlomieju** [comment]
Thanks, this seems it's already fixed.

**Comment by silvioprog** [comment]
Not fixed. At least at [main](https://github.com/denoland/manual/blob/main/getting_started/first_steps.md).

But no problem, we can close this without solving the warning.

**Comment by bartlomieju** [comment]
Ah, good eyes, indeed `request: Request` is not fixed yet, I think we should do `_request: Request`.
