### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by silvioprog** [denoland/manual#480]
Page not found for link [`lib.deno.unstable.d.ts`](https://github.com/denoland/deno/blob/v1.28.3/cli/dts/lib.deno.unstable.d.ts) at [`Troubleshooting`](https://deno.land/manual@v1.28.3/basics/standard_library).

**Comment by silvioprog** [comment]
Same for [lib.deno.ns.d.ts](https://github.com/denoland/deno/blob/v1.28.3/cli/dts/lib.deno.ns.d.ts) at [`Deno global`](https://deno.land/manual@v1.28.3/runtime#deno-global).

**Comment by GJZwiers** [comment]
This one is also broken in [Stability](https://deno.land/manual@v1.28.3/runtime/stability), for which I made a fix in #469. I can update it to also include fixes for these two links.
