### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by silvioprog** [denoland/manual#481]
Please notice the missing image below:

<img width="261" alt="Screen Shot 2022-12-04 at 2 33 16 PM" src="https://user-images.githubusercontent.com/1456829/205506157-9e239532-2471-472d-b350-222293dcf06e.png">

At [`Schematic diagram`](https://deno.land/manual@v1.28.3/references/contributing/architecture#schematic-diagram).

**Comment by kt3k** [comment]
duplicate of https://github.com/denoland/manual/issues/235
