### ISSUE TITLE
await p.status() before await p.output() blocks: Is the order correct?

### ISSUE THREAD

**Issue by guest271314** [denoland/manual#500]
https://deno.land/manual@v1.29.1/examples/subprocess#communicating-with-subprocesses

```
const { code } = await p.status();

// Reading the outputs closes their pipes
const rawOutput = await p.output();
```

**Comment by kt3k** [comment]
I think the example should call `.status()`, `.output()`, and `.stderrOutput()` at the same time (before `await`ing any of them). So the example should be something like:

```js
const [{ code }, rawOutput, rawError] = await Promise.all([
  p.status(),
  p.output(),
  p.stderrOutput(),
]);
```

cc @bartlomieju

**Comment by bartlomieju** [comment]
Yes @kt3k, that would be preferable.
