### ISSUE TITLE
Exact word search (or improve search result)

### ISSUE THREAD

**Issue by xnuk** [denoland/manual#515]
I wonder if this is right place, but I was finding Deno manuals, so I'm writing here.

I hoped `deno lsp` and `deno check` can understand DOM in TypeScript file, and at that instant, the keyword `deno.ns` pop into my head. Maybe I did same thing before. So I visited [deno.land](https://deno.land) and searched that keyword:

| Keyword `deno.ns` | Keyword `"deno.ns"` |
|-------------------|---------------------|
| ![Search result with 'deno.ns' keyword. No results are highlighted with the exact keyword. In "Manual" section, results are: "Continuous Integration", "Integration with testing libraries", "Standard modules", "Custom Messages", "Metrics". In "Modules" section, results are: "denops_std", "denon", "denops_core", "denosass", "denops_defer".](https://user-images.githubusercontent.com/3071003/210568101-0be34a67-9d33-4a1f-a872-b2524e6afb6e.png) | ![Same with previous result but the keyword is dobule-quoted.](https://user-images.githubusercontent.com/3071003/210568612-6964940c-ae37-468b-81d7-ace639ee5b0d.png) |

No results have the exact keyword `deno.ns`. But in DuckDuckGo: the second result 'Configuration | Manual | Deno' has the keyword, and that's what I wanted. 

![DuckDuckGo Search result of 'site:deno.land deno.ns'. Some results are highlighted with the exact keyword "deno.ns", one of these is "Configuration | Manual | Deno - DenoLand".](https://user-images.githubusercontent.com/3071003/210569181-fc54a320-7f6c-4707-89fc-da9569bb4927.png)

Similar thing happens with the keyword `@deno-types`: In deno.land result, first and second link doesn't have the keyword, only the third link contains the word `@deno-types`.

![`@deno-types` result in deno.land](https://user-images.githubusercontent.com/3071003/210571323-69d1832b-9c32-41e0-959f-2fbb4fb3fd86.png)

So what I want to say is, the search result is somehow poor than my expectation. Adding double-quotes doesn't do exact word search, and order of result is curious.

### Expected
If I search `deno.ns` or `"deno.ns"` in deno.land, at least one of the top 5 'Manual' search results should contain the word `deno.ns`.

### Actual
In the top 5 search result, no one contains the word `deno.ns`.

**Comment by kwhinnery** [comment]
It does appear in search now, thx!
