### ISSUE TITLE
Support non-version-specific /latest/ URL for Deno docs

### ISSUE THREAD

**Issue by zachtil** [denoland/manual#516]
Hi 👋 

When you want to link to Deno docs, you currently have to use a version-specific URL, such as `https://deno.land/manual@v1.29.1/getting_started/installation`.

Can you also support a standard `latest` / `current` URL (e.g. `https://deno.land/latest/getting_started/installation`) that always points to the current Deno docs version?

**Comment by davbrito** [comment]
You can just link to https://deno.land/manual/getting_started/installation and it will redirect to the latest version.

**Comment by zachtil** [comment]
Thank you @davbrito! That's what I needed!
