### ISSUE TITLE
Error in configuration file manual

### ISSUE THREAD

**Issue by Overdoos** [denoland/manual#608]
If you follow the tutorial for setting up a configuration file, you may notice an error when importing the library.
https://deno.land/manual@v1.32.3/getting_started/configuration_file at line 36
An s is missing. 
![image](https://user-images.githubusercontent.com/37914910/230630614-e2167ea8-dec1-42c3-9b2a-b114697f8ccd.png)

**Comment by kwhinnery** [comment]
assert/
