### ISSUE TITLE
Unable to view architecture diagram

### ISSUE THREAD

**Issue by k-nasa** [denoland/manual#661]
I can't view the architecture diagram.

https://deno.com/manual@v1.33.4/references/contributing/architecture

There is an architecture diagram on this page, but the link is broken and I can't see it.
I think this is important for those who start learning DENO. (At least I want one!)

I looked for your org but no diagram existed.

**Comment by kwhinnery** [comment]
I have removed this for now, I couldn't find the original image either. I think we'd need to approach this as a new piece of content anyway: https://github.com/denoland/deno-docs/issues/79
