### ISSUE TITLE
"Getting started" sample is incorrect

### ISSUE THREAD

**Issue by erymski** [denoland/manual#670]
Executing
https://github.com/denoland/manual/blob/72f44470a7dede201a71c1f8e9b3d2960233d6e7/getting_started/first_steps.md?plain=1#L85-L87

gives:
```
❯ deno run --allow-net=deno.land first_steps.ts
┌ ⚠️  Deno requests net access to "deno.com".
├ Requested by `fetch()` API.
├ Run again with --allow-net to bypass this prompt.
└ Allow? [y/n/A] (y = yes, allow; n = no, deny; A = allow all net permissions) >
```

It can be solved with changing the command line a bit:
```
❯ deno run --allow-net=deno.land,deno.com first_steps.ts
```
but I guess it's better to change the description as well

----------
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045

deno 1.34.1 (release, x86_64-pc-windows-msvc)
v8 11.5.150.2
typescript 5.0.4

**Comment by PoignardAzur** [comment]
Fixed in #675 if I understand correctly.
