### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by GmBodhi** [denoland/manual#68]
[Fetch API](https://deno.land/manual/examples/fetch_data)
The docs don't seem to be updated yet.
![image](https://user-images.githubusercontent.com/71921036/131209225-fb208cd4-43c4-4729-a66f-bc07081bf0dd.png)
It's missing an `await`. I've noticed that the main branch is having the fix, but it's not updated on the site.

**Comment by satyarohith** [comment]
> It's missing an await. I've noticed that the main branch is having the fix, but it's not updated on the site.

The docs will be updated when there's a new release of https://github.com/denoland/deno. Please use the version of the main branch for the time being.
