### ISSUE TITLE
The rendering of the manual has become proprietary

### ISSUE THREAD

**Issue by not-my-profile** [denoland/manual#688]
The [dotland repository](https://github.com/denoland/dotland) has been archived for [some reason](https://github.com/denoland/website_feedback/issues/34), which means that you can no longer reliably locally preview your contributions to the manual, since the rendering may have changed since the dotland repository has been archived.

**Comment by ry** [comment]
We'll be moving the manual rendering to docusaurus soon and we will be open sourcing that.

**Comment by jollytoad** [comment]
What about the rendering of the /x modules? It's difficult to document modules, and provide useful feedback on the site without a transparent rendering process.

**Comment by kwhinnery** [comment]
- New docs repo - https://github.com/denoland/deno-docs
- Point taken on the docs rendering for /x - captured as a feedback issue: https://github.com/denoland/website_feedback/issues/51
