### ISSUE TITLE
New manual website

### ISSUE THREAD

**Issue by lucacasonato** [denoland/manual#9]
Now that the manual is moved out of the main repo, it is a great time to improve the manual website. Here are the primary design constraints:

- Run on Deno for local development, and Deno Deploy for production
- Server side rendered
- Support a light and dark theme
- High quality OpenGraph metadata (for example for Twitter cards)
- High quality markdown rendering with a good markdown stylesheet
- Accessible & easy to use on mobile and desktop
- 100/100/100/100 Lighthouse score
- Test coverage
- Integrate Algolia DocSearch like the current site does
- No, or very very minimal client side JS. None should be required for first render, then <10 KB for progressive enhancement

**Comment by lmx-Hexagram** [comment]
Cool! And I also think i18n supported is required. If deno want developers who use different language read manual in an easier way.

**Comment by kt3k** [comment]
stale
